name: EAS Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Build APK
        env:
          EXPO_TOKEN: ${{ secrets.EAS_TOKEN }}
        run: eas build -p android --profile preview --non-interactive
